# Generated by Django 5.1.2 on 2024-10-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_rename_row_ticket_rows_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='crew',
            field=models.ManyToManyField(to='airport.crew'),
        ),
    ]
