# Generated by Django 5.1.2 on 2024-10-14 12:26

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0006_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=airport.models.crew_image_path),
        ),
    ]
