# Generated by Django 5.1.2 on 2024-10-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0007_crew_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='crew',
            field=models.ManyToManyField(blank=True, to='airport.crew'),
        ),
    ]
